<div class="container-fluid footercpt">
<div class="container">
<div class="row">
<div class="col-lg-12"><img id="logoBlanco" src="<?php echo $this->helper('\Magento\Cms\Helper\Wysiwyg\Images')->getBaseUrl().'cuero-papel-tijera-logo-blanco.png' ?>" alt="Logo Cuero, Papel y Tijera"></div>
<div class="col-lg-4 listaFooter">
<ul>
<li><a href="sofia-protti" alt="Sofia Protti">Sofía Protti</a></li>
<li><a href="conocenos" alt="Conocenos">Con&oacute;cenos</a></li>
<li><a href="blog" alt="Blog">Blog</a></li>
<li><a href="tiendas" alt="Tiendas">Tiendas</a></li>
</ul>
</div>
<div class="col-lg-4"><img class="redesSociales redesSocialesAll" src="<?php echo $this->helper('\Magento\Cms\Helper\Wysiwyg\Images')->getBaseUrl().'logo-facebook.png'; ?>" alt=""> <img class="redesSocialesAll" src="<?php echo $this->helper('\Magento\Cms\Helper\Wysiwyg\Images')->getBaseUrl().'logo-pinterest.png'; ?>" alt=""> <img class="redesSocialesAll" src="<?php echo $this->helper('\Magento\Cms\Helper\Wysiwyg\Images')->getBaseUrl().'logo-instagram.png'; ?>" alt=""> <img class="separadorFooter" src="<?php echo $this->helper('\Magento\Cms\Helper\Wysiwyg\Images')->getBaseUrl().'separador-footer.png'; ?>" alt=""></div>
<div class="col-lg-4 listaFooter">
<ul>
<li><a href="distribuir" alt="Distribuir">Distribuir</a></li>
<li><a href="contactanos" alt="Contáctenos">Contáctenos</a></li>
<li><a href="devoluciones" alt="Política de devoluciones">Política de devoluciones</a></li>
<li><a href="envio" alt="Política de envío">Política de envío</a></li>
<li><a href="privacidad" alt="Política de Privacidad">Políticas de privacidad</a></li>
</ul>
</div>
</div>
<div class="row">
<div class="col-lg-4">&nbsp;</div>
<div class="col-lg-4">
<h4 id="suscribirseFooter">Suscríbase a nuestro boletín</h4>
<form><input id="email" name="email" type="text" placeholder="Email"> <input id="suscribirme" type="submit" value="Suscribirme"></form></div>
<div class="col-lg-4">&nbsp;</div>
</div>
</div>
</div>